version: "3.8"

services:

  database:
    container_name: database
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_DB: ${SQL_NAME}
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
    volumes:
    - database:/data/
    ports:
    - "5432:5432"
    networks:
      - sql

  api_gateway:
    container_name: api_gateway
    build:
      ./
    command: uvicorn main:gateway_api --host 0.0.0.0 --port 9000
    ports:
      - "9000:9000"
    networks:
      - sql
      - nginx
    develop:
      watch:
        - action: sync
          path: src/gateway
          target: src/settings
          ignore:
            - .git
            - .github
            - .idea
            - .venv
            - .gitignore
            - README.md
        - action: sync
          path: /src/gateway
          target: src/gateway
        - action: sync
          path: /src/settings
          target: src/settings
        - action: sync
          path: main.py
          target: main.py
        - action: rebuild
          path: pyproject.toml

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - protocol: tcp
        target: 8000
        published: 8881
    environment:
      NGINX_PORT: 80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - nginx
    depends_on:
      - api_gateway

networks:
    sql:
      external: true
    nginx:
      external: true

volumes:
  database: